SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[ProgressiveVaccinations]
  FROM [PortfolioProject].[dbo].[PercentVaccinated]
